import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import Image from "next/image";

export const metadata = {
  title: "Diogo Alpendre",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="relative h-screen w-screen text-white">
        <Image
          src="/img/coding_wallpaper-js.webp"
          alt="Coding background"
          fill
          className="object-cover z-0 opacity-30"
          priority
        />
        <div className="flex flex-col">

          <nav className="fixed top-0 inset-x-0 z-50 h-14 border-white/10 bg-cyan-950/40">
            <div className="mx-auto max-w-6xl px-4 sm:px-6 h-full flex items-center justify-between">
              <a
                href="#"
                className="font-semibold text-white no-underline hover:underline underline-offset-2"
              >
                <span className="font-bold text-xl">Diogo </span><span className="font-light text-xl">Alpendre</span>
              </a>

              <a
                className="hidden sm:inline-flex text-white h-8 items-center rounded-full border border-white/15 px-3 text-xs hover:bg-white/10"
                href={`mailto:${process.env.NEXT_PUBLIC_EMAIL}`}
              >
                Talk to me
              </a>
            </div>
          </nav>

          <main className="flex-1 pt-14 pb-16 overflow-y-auto">
            {children}
          </main>
          
          <footer className="fixed bottom-0 inset-x-0 border-t border-white/10 bg-black py-4 flex items-center justify-center gap-6 z-50">
            <a
              className="flex items-center gap-2 text-white !no-underline hover:underline-offset-4"
              href={process.env.NEXT_PUBLIC_GITHUB}
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image aria-hidden src="/github-color.svg" alt="GitHub" width={16} height={16} />
              GitHub
            </a>
            <a
              className="flex items-center gap-2 text-white !no-underline hover:underline-offset-4"
              href={process.env.NEXT_PUBLIC_LINKEDIN}
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image aria-hidden src="/linkedin-color.svg" alt="LinkedIn" width={16} height={16} />
              Linkedin
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}
